version: '3'

services:
  database:
    image: mysql
    container_name: database
    env_file:
      - database.env
  backend:
    image: nolan2002/backend:latest
    container_name: backend
    user: backend
    env_file:
      - backend.env
    depends_on:
      - database
  data:
    image: nolan2002/data:latest
    container_name: data
    user: root
    env_file:
      - data.env
    depends_on:
      - backend
  web:
    image: nolan2002/frontend:latest
    container_name: web
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    env_file:
      - web.env
    depends_on:
      - database
      - backend